apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
    REDIS_HOST: "redis-master"
    REDIS_PORT: "6379"
    USERNAME: "bob"
    PASSWORD: "thebuilder"
    THEBIGSECRET: "I love brownies!"