apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 422434854706.dkr.ecr.us-east-1.amazonaws.com/bloomreach-challenge-app
  newTag: d6cbdc0df33ef5f5dce803931e4d89031865223b
- name: frontend
  newName: bloomreach-challenge-app
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: bloomreach-challenge-app
  newName: bloomreach-challenge-app
  newTag: new