name: Build and Push an Image to ECR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: '422434854706'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: bloomreach-challenge-app
  ECR_REPOSITORY: 422434854706.dkr.ecr.us-east-1.amazonaws.com/bloomreach-challenge-app

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Add steps here like linting, testing, minification, etc.
      
    # Add steps here like linting, testing, minification, etc.

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag the image
      run: |
        SHORT_SHA=${GITHUB_SHA}

        # Build and tag the image
        docker build \
          -t $CONTAINER_IMAGE \
          -t 422434854706.dkr.ecr.us-east-1.amazonaws.com/bloomreach-challenge-app:master-$SHORT_SHA ./app
    
    # Add additional steps here like scanning of image

    # Only push to registry on master
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        SHORT_SHA=${GITHUB_SHA}

        # Push image to AWS ECR
        docker push 422434854706.dkr.ecr.us-east-1.amazonaws.com/bloomreach-challenge-app:master-$SHORT_SHA

    - name: Deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: bloomreach-challenge-app
        IMAGE_TAG: ${{ github.sha }}
      with:
        args: set image deployment/$ECR_REPOSITORY $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/bloomreach-challenge-app
